[plugins]

lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube-plugin" }

spotless = { id = "com.diffplug.spotless", version.ref = "spotless-plugin" }

com-diffplug-spotless = { id = "com.diffplug.spotless", version.ref = "spotless-plugin" }

io-freefair-lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }

com-gradleup-shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin" }

org-sonarqube = { id = "org.sonarqube", version.ref = "sonarqube-plugin" }

[versions]

commons-lang3 = "3.20.0"
commons-collections4 = "4.5.0"
spotbugs-annotations = "4.9.4"
junit = "5.12.1"
lombok-plugin = "9.1.0"
shadow-plugin = "9.2.2"
sonarqube-plugin = "7.1.0.6387"
spotless-plugin = "8.1.0"

[libraries]

commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "commons-collections4" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }
